name: "publish package to npm"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: "Setup FFmpeg"
        uses: FedericoCarboni/setup-ffmpeg@v3
      - name: build
        run: npm install && npm run tsc-build
      - name: test
        run: npx vitest run
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish --access public
